version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: nano-graphrag-redis
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    environment:
      # Redis configuration via environment variables
      REDIS_ARGS: "--appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - redis_config:/usr/local/etc/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - nano-graphrag-network

volumes:
  redis_data:
    driver: local
  redis_config:
    driver: local

networks:
  nano-graphrag-network:
    driver: bridge
    name: nano-graphrag-network